export default [
    // General / Title
    {
        id: 1,
        category_name: "General",
        category_id: 1,
        meaning: "Overall Experience",
        parent_question: "Give your review a short title (max 120 characters).",
        student_question: "Give your review a short title (max 120 characters).",
        teacher_question: "Give your review a short title (max 120 characters).",
        parent_code: "EX_01_P",
        student_code: "EX_01_S",
        teacher_code: "EX_01_T",
    },

    // --- Student & Parent Learning Category (category_id: 2) ---
    {
        id: 2,
        category_name: "Learning",
        category_id: 2,
        meaning: "Learning Support",
        parent_question: "My child gets the support they need to learn.",
        student_question: "I get the support I need to learn.",
        parent_code: "AC_01_P",
        student_code: "AC_01_S",
    },
    {
        id: 3,
        category_name: "Learning",
        category_id: 2,
        meaning: "Individual Learning Support",
        parent_question: "Teachers notice when my child needs help.",
        student_question: "Teachers notice when I need help.",
        parent_code: "AC_02_P",
        student_code: "AC_02_S",
    },
    {
        id: 4,
        category_name: "Learning",
        category_id: 2,
        meaning: "Homework Load",
        parent_question: "Homework is manageable.",
        student_question: "Homework is manageable.",
        parent_code: "AC_03_P",
        student_code: "AC_03_S",
    },
    {
        id: 5,
        category_name: "Learning",
        category_id: 2,
        meaning: "Future Readiness",
        parent_question: "Students are prepared for next steps.",
        student_question: "I know my options after school.",
        parent_code: "FR_01_P",
        student_code: "FR_01_S",
    },

    // --- Wellbeing Category (category_id: 3) ---
    {
        id: 6,
        category_name: "Wellbeing",
        category_id: 3,
        meaning: "Safety",
        parent_question: "The school is safe.",
        student_question: "I feel safe at school.",
        teacher_question: "I feel safe at school.",
        parent_code: "WB_01_P",
        student_code: "WB_01_S",
        teacher_code: "WB_03_T",
    },
    {
        id: 7,
        category_name: "Wellbeing",
        category_id: 3,
        meaning: "Student Wellbeing",
        parent_question: "My child feels happy and supported.",
        student_question: "I feel happy and supported.",
        parent_code: "WB_02_P",
        student_code: "WB_02_S",
    },
    {
        id: 101,
        category_name: "Wellbeing",
        category_id: 3,
        meaning: "Workload",
        teacher_question: "My workload is manageable.",
        teacher_code: "WB_01_T",
    },
    {
        id: 102,
        category_name: "Wellbeing",
        category_id: 3,
        meaning: "Staff Wellbeing",
        teacher_question: "Staff wellbeing is supported.",
        teacher_code: "WB_02_T",
    },

    // --- Student & Parent Teaching Category (category_id: 4) ---
    {
        id: 8,
        category_name: "Teaching",
        category_id: 4,
        meaning: "Teaching Quality",
        parent_question: "Teaching is high quality.",
        student_question: "Teaching is high quality.",
        parent_code: "TL_01_P",
        student_code: "TL_01_S",
    },
    {
        id: 9,
        category_name: "Teaching",
        category_id: 4,
        meaning: "School Communication",
        parent_question: "The school communicates clearly.",
        student_question: "The school keeps students informed.",
        parent_code: "TL_02_P",
        student_code: "TL_02_S",
    },
    {
        id: 10,
        category_name: "Teaching",
        category_id: 4,
        meaning: "Leadership",
        parent_question: "School leadership is effective.",
        student_question: "School leaders make decisions that benefit students.",
        parent_code: "TL_03_P",
        student_code: "TL_03_S",
    },
    {
        id: 11,
        category_name: "Teaching",
        category_id: 4,
        meaning: "Classroom Management",
        parent_question: "Classes are well managed.",
        student_question: "Classes are calm and focused.",
        parent_code: "TL_04_P",
        student_code: "TL_04_S",
    },

    // --- Student & Parent Community Category (category_id: 5) ---
    {
        id: 12,
        category_name: "Community",
        category_id: 5,
        meaning: "Fairness",
        parent_question: "Students are treated fairly.",
        student_question: "I am treated fairly.",
        parent_code: "CI_01_P",
        student_code: "CI_01_S",
    },
    {
        id: 13,
        category_name: "Community",
        category_id: 5,
        meaning: "Inclusion",
        parent_question: "The school is welcoming to all families.",
        student_question: "I feel welcome at school.",
        parent_code: "CI_03_P",
        student_code: "CI_03_S",
    },
    {
        id: 14,
        category_name: "Community",
        category_id: 5,
        meaning: "Voice",
        parent_question: "Parents are listened to.",
        student_question: "Students are listened to.",
        parent_code: "CI_04_P",
        student_code: "CI_04_S",
    },

    // --- Student & Parent Facilities Category (category_id: 6) ---
    {
        id: 15,
        category_name: "Facilities",
        category_id: 6,
        meaning: "Activities",
        parent_question: "The school offers many activities.",
        student_question: "There are activities I can join.",
        parent_code: "AF_01_P",
        student_code: "AF_01_S",
    },
    {
        id: 16,
        category_name: "Facilities",
        category_id: 6,
        meaning: "Facilities",
        parent_question: "Facilities are clean and well maintained.",
        student_question: "Facilities are clean and well maintained.",
        parent_code: "AF_02_P",
        student_code: "AF_02_S",
    },
    {
        id: 17,
        category_name: "Facilities",
        category_id: 6,
        meaning: "Value for Money",
        parent_question: "The school offers good value for money.",
        student_question: "*",
        parent_code: "VL_01_P",
        student_code: "*",
    },

    // --- Teacher Leadership Category (category_id: 8) ---
    {
        id: 103,
        category_name: "Leadership",
        category_id: 8,
        meaning: "Leadership",
        teacher_question: "School leadership is effective.",
        teacher_code: "TL_01_T",
    },
    {
        id: 104,
        category_name: "Leadership",
        category_id: 8,
        meaning: "Voice",
        teacher_question: "Staff input is valued.",
        teacher_code: "TL_02_T",
    },
    {
        id: 105,
        category_name: "Leadership",
        category_id: 8,
        meaning: "Communication",
        teacher_question: "Communication is clear and timely.",
        teacher_code: "TL_03_T",
    },

    // --- Teacher Culture Category (category_id: 9) ---
    {
        id: 106,
        category_name: "Culture",
        category_id: 9,
        meaning: "Team Culture",
        teacher_question: "Staff work well together.",
        teacher_code: "CI_01_T",
    },
    {
        id: 107,
        category_name: "Culture",
        category_id: 9,
        meaning: "Fairness & Inclusion",
        teacher_question: "Staff are treated fairly and with respect.",
        teacher_code: "CI_02_T",
    },
    {
        id: 108,
        category_name: "Culture",
        category_id: 9,
        meaning: "Teaching Quality",
        teacher_question: "Teaching standards are high.",
        teacher_code: "TL_04_T",
    },

    // --- Teacher Resources & Growth Category (category_id: 10) ---
    {
        id: 109,
        category_name: "Resources & Growth",
        category_id: 10,
        meaning: "Resources",
        teacher_question: "I have the resources I need to do my job well.",
        teacher_code: "RG_01_T",
    },
    {
        id: 110,
        category_name: "Resources & Growth",
        category_id: 10,
        meaning: "Professional Growth",
        teacher_question: "I receive feedback that helps me improve.",
        teacher_code: "RG_02_T",
    },
    {
        id: 111,
        category_name: "Resources & Growth",
        category_id: 10,
        meaning: "Compensation",
        teacher_question: "I feel fairly compensated for my role.",
        teacher_code: "RG_03_T",
    },
    {
        id: 112,
        category_name: "Resources & Growth",
        category_id: 10,
        meaning: "Facilities",
        teacher_question: "Facilities are clean and well maintained.",
        teacher_code: "RG_04_T",
    },

    // --- Recommendation & Open Comments ---
    {
        id: 18,
        category_name: "General",
        category_id: 1,
        meaning: "Recommendation",
        parent_question: "I would recommend this school.",
        student_question: "I would recommend this school to a friend.",
        teacher_question: "I would recommend this school as a workplace.",
        parent_code: "RE_01_P",
        student_code: "RE_01_S",
        teacher_code: "OV_01_T",
    },
    {
        id: 19,
        category_name: "Open Comments",
        category_id: 7,
        meaning: "Strengths",
        parent_question: "What’s working well at this school?",
        student_question: "What do you like most about your school?",
        teacher_question: "What’s working well at this school?",
        parent_code: "OP_01_P",
        student_code: "OP_01_S",
        teacher_code: "SM_01_T",
    },
    {
        id: 20,
        category_name: "Open Comments",
        category_id: 7,
        meaning: "Areas for Improvement",
        parent_question: "What could the school do better?",
        student_question: "What could make your school better?",
        teacher_question: "What could the school do better?",
        parent_code: "OP_02_P",
        student_code: "OP_02_S",
        teacher_code: "SM_02_T",
    },
]